apiVersion: v1
kind: Service
metadata:
  name: docker-api
spec:
  selector:
    app: docker-api
  type: LoadBalancer # Expose service through a Load Balancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
